"""
Phase 5 orchestrator: runs the full Pandas analysis layer, generates all
figures, and writes a markdown insights report.

Run from the project root (after src/etl/load_to_db.py):
    python -m src.analysis.generate_report
"""

import time

import pandas as pd

from src import config
from src.analysis import visualizations as viz
from src.analysis.abc_analysis import (
    abc_summary,
    classify_abc,
    inventory_turnover_by_category,
)
from src.analysis.db import load_inventory_detail, load_sales_detail, load_table
from src.analysis.dead_stock import (
    analyze_dead_stock,
    dead_stock_by_category,
    dead_stock_summary,
)
from src.analysis.supplier_scorecard import (
    build_supplier_scorecard,
    validate_scorecard_against_seed,
)

REPORTS_DIR = config.PROJECT_ROOT / "reports"


def _fmt_money(value: float) -> str:
    if abs(value) >= 1_000_000:
        return f"${value / 1_000_000:,.1f}M"
    return f"${value:,.0f}"


def main() -> None:
    start = time.time()
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    config.PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)
    viz.apply_house_style()

    print("Loading data...")
    sales = load_sales_detail()
    inventory = load_inventory_detail()
    orders = load_table("orders").merge(
        load_table("warehouses")[["warehouse_id", "name"]].rename(
            columns={"name": "warehouse_name"}
        ),
        on="warehouse_id",
    )

    print("Running ABC analysis...")
    abc = classify_abc(sales)
    abc_sum = abc_summary(abc)
    abc.to_csv(config.PROCESSED_DATA_DIR / "abc_classification.csv", index=False)
    abc_sum.to_csv(config.PROCESSED_DATA_DIR / "abc_summary.csv", index=False)

    print("Computing inventory turnover...")
    turnover = inventory_turnover_by_category(sales, inventory)
    turnover.to_csv(config.PROCESSED_DATA_DIR / "inventory_turnover.csv", index=False)

    print("Building supplier scorecard...")
    scorecard = build_supplier_scorecard()
    validation = validate_scorecard_against_seed(scorecard)
    scorecard.to_csv(config.PROCESSED_DATA_DIR / "supplier_scorecard.csv", index=False)

    print("Analyzing dead stock...")
    dead = analyze_dead_stock()
    dead_sum = dead_stock_summary(dead)
    dead_cat = dead_stock_by_category(dead)
    dead.to_csv(config.PROCESSED_DATA_DIR / "dead_stock_detail.csv", index=False)
    dead_sum.to_csv(config.PROCESSED_DATA_DIR / "dead_stock_summary.csv", index=False)

    print("Generating figures...")
    figures = [
        viz.plot_monthly_revenue_trend(sales),
        viz.plot_warehouse_comparison(sales, orders),
        viz.plot_abc_pareto(abc),
        viz.plot_inventory_turnover(turnover),
        viz.plot_supplier_risk(scorecard),
        viz.plot_inventory_health_mix(dead_sum),
        viz.plot_dead_stock_by_category(dead_cat),
    ]
    for f in figures:
        print(f"  {f}")

    print("Writing insights report...")
    report = _build_report(sales, inventory, abc_sum, turnover, scorecard,
                           validation, dead_sum, dead_cat)
    report_path = REPORTS_DIR / "insights_report.md"
    report_path.write_text(report)

    elapsed = time.time() - start
    print(f"\nDone in {elapsed:.1f}s.")
    print(f"Report: {report_path.relative_to(config.PROJECT_ROOT)}")
    print(f"Figures: {viz.FIGURES_DIR.relative_to(config.PROJECT_ROOT)}/ ({len(figures)} charts)")


def _build_report(sales, inventory, abc_sum, turnover, scorecard,
                  validation, dead_sum, dead_cat) -> str:
    total_revenue = sales["line_revenue"].sum()
    total_margin = sales["line_margin"].sum()
    margin_pct = 100 * total_margin / total_revenue
    total_inventory_value = inventory["inventory_value"].sum()

    a_row = abc_sum[abc_sum["abc_class"] == "A"].iloc[0]
    high_risk = scorecard[scorecard["risk_tier"] == "High Risk"]
    worst = scorecard.iloc[0]

    dead_row = dead_sum[dead_sum["stock_status"] == "Dead"]
    dead_value = dead_row["total_value"].iloc[0] if len(dead_row) else 0
    dead_pct = dead_row["pct_of_inventory_value"].iloc[0] if len(dead_row) else 0

    problem_value = dead_cat["capital_tied_up"].sum()
    worst_cat = dead_cat.iloc[0] if len(dead_cat) else None

    fastest = turnover.dropna(subset=["inventory_turnover"]).iloc[0]
    slowest = turnover.dropna(subset=["inventory_turnover"]).iloc[-1]

    return f"""# NovaLog Distribution — Inventory & Supply Chain Insights

Generated by `src/analysis/generate_report.py`. All figures in
`reports/figures/`. All underlying tables in `data/processed/`.

> Scope note: revenue figures cover **delivered orders only**. Cancelled
> and returned orders are excluded, since they produced no realized
> revenue. Returns are analyzed separately as a warehouse quality metric.

## Headline numbers

| Metric | Value |
|---|---|
| Delivered revenue | {_fmt_money(total_revenue)} |
| Gross margin | {_fmt_money(total_margin)} ({margin_pct:.1f}%) |
| Inventory value at cost | {_fmt_money(total_inventory_value)} |
| Capital in dead stock | {_fmt_money(dead_value)} ({dead_pct:.1f}% of inventory) |
| Capital in dead + slow-moving | {_fmt_money(problem_value)} |
| Suppliers flagged High Risk | {len(high_risk)} of {len(scorecard)} |

## 1. Revenue concentration (ABC analysis)

{a_row['pct_of_skus']:.1f}% of SKUs (class A, {int(a_row['sku_count'])} products) generate
{a_row['pct_of_revenue']:.1f}% of revenue — a textbook Pareto distribution.

**So what:** class A items justify tight inventory control, frequent review
cycles, and priority allocation of warehouse space. Class C items
({abc_sum[abc_sum['abc_class'] == 'C']['pct_of_skus'].iloc[0]:.0f}% of SKUs
for {abc_sum[abc_sum['abc_class'] == 'C']['pct_of_revenue'].iloc[0]:.1f}% of
revenue) should be managed with minimal overhead — larger, less frequent
orders, or candidates for delisting.

![ABC Pareto](figures/abc_pareto.png)

## 2. Inventory turnover

{fastest['category']} turns over fastest at {fastest['inventory_turnover']:.2f}x
per year ({fastest['days_of_supply']:.0f} days of supply). {slowest['category']}
is slowest at {slowest['inventory_turnover']:.2f}x
({slowest['days_of_supply']:.0f} days of supply).

**So what:** slow-turning categories are where working capital goes to sit.
They're the first place to look for order-quantity reductions.

> Methodology caveat: this dataset holds a single current inventory
> snapshot rather than a historical series, so turnover uses ending
> inventory rather than true average inventory. Cross-category comparison
> is valid; absolute values are approximate.

![Inventory turnover](figures/inventory_turnover.png)

## 3. Supplier reliability

{len(high_risk)} suppliers fall into the **High Risk** tier. The weakest performer
is **{worst['supplier_name']}** ({worst['region']}) with a composite score of
{worst['composite_score']:.1f}/100 — {worst['late_delivery_rate_pct']:.0f}% of its
deliveries arrive late, averaging {worst['avg_delay_days']:.1f} days behind schedule.

The composite score weights on-time rate (50%), average delay severity
(30%), and delay consistency (20%). Consistency earns its own weight
because a predictably-late supplier can be planned around; an erratic one
cannot.

**Methodology validation:** the scorecard is built purely from observed
delivery behavior. Correlating it afterwards against the hidden generation
parameter gives **r = {validation['correlation']}** — {validation['interpretation'].lower()}.
This confirms the scoring recovers genuine underlying reliability rather
than fitting noise.

![Supplier risk](figures/supplier_risk.png)

## 4. Dead stock

{_fmt_money(dead_value)} ({dead_pct:.1f}% of total inventory value) sits in
positions with **zero sales in the last 90 days** and stock at 2x safety
level or above.

Note the distinction the classification draws: *Overstocked* inventory is
high but still selling and will clear on its own. *Dead* inventory is
stranded capital that needs intervention — markdown, liquidation, or
write-off. A stock-level-only view cannot tell these apart.

{f"**{worst_cat['category']}** carries the most at-risk capital at {_fmt_money(worst_cat['capital_tied_up'])}." if worst_cat is not None else ""}

![Inventory health](figures/inventory_health_mix.png)

![Dead stock by category](figures/dead_stock_by_category.png)

## 5. Warehouse performance

Revenue scale and operational quality are shown side by side deliberately:
ranking warehouses on revenue alone would reward the largest facility even
if it had the worst return rate.

![Warehouse comparison](figures/warehouse_comparison.png)

![Monthly revenue](figures/monthly_revenue_trend.png)

## Recommended actions

1. **Differentiate inventory policy by ABC class** — tighten review cycles
   on class A SKUs, reduce management overhead on class C.
2. **Open supplier reviews with the {len(high_risk)} High Risk suppliers**, starting with
   {worst['supplier_name']}. Where dual-sourcing isn't viable, increase safety
   stock on affected SKUs to absorb their lead time variability.
3. **Run a liquidation review on dead stock**, prioritizing
   {worst_cat['category'] if worst_cat is not None else 'the highest-value categories'},
   to release working capital.
4. **Reduce order quantities in slow-turning categories** to stop the
   problem regenerating after liquidation.
"""


if __name__ == "__main__":
    main()
